#!/usr/bin/env bash

DIOPI_IMPL=${3:-camb}
DIPU_DEVICE=${2:-camb}

function build_dipu_py() {
    export CMAKE_BUILD_TYPE=debug
    export _GLIBCXX_USE_CXX11_ABI=1
    export MAX_JOBS=12
    # PYTORCH_INSTALL_DIR is /you_pytorch/torch20/pytorch/torch
    # python  setup.py build_clib 2>&1 | tee ./build1.log
    python setup.py build_ext 2>&1 | tee ./build1.log
    cp build/python_ext/torch_dipu/_C.cpython-38-x86_64-linux-gnu.so torch_dipu
}

function config_dipu_cmake() {
    cd ./build && rm -rf ./*
    PYTORCH_DIR="/you_pytorch/torch20/pytorch"
    PYTHON_INCLUDE_DIR="/you_conda/envs/torch20/include/python3.8"
    # export NEUWARE_ROOT="/usr/local/neuware-2.4.1/"
    cmake ../  -DCMAKE_BUILD_TYPE=Debug \
     -DDEVICE=${DIPU_DEVICE} -DPYTORCH_DIR=${PYTORCH_DIR} \
     -DPYTHON_INCLUDE_DIR=${PYTHON_INCLUDE_DIR}
      # -DCMAKE_C_FLAGS_DEBUG="-g -O0" \
      # -DCMAKE_CXX_FLAGS_DEBUG="-g -O0"
    cd ../
}


function autogen_diopi_wrapper() {
    python scripts/autogen_diopi_wrapper/autogen_diopi_wrapper.py \
        --config scripts/autogen_diopi_wrapper/diopi_functions.yaml \
            --out torch_dipu/csrc_dipu/aten/ops/AutoGenedKernels.cpp
}

function build_diopi_lib() {
    cd third_party/DIOPI/DIOPI-IMPL
    sh scripts/build_impl.sh clean
    sh scripts/build_impl.sh ${DIOPI_IMPL}
    cd -
}

function build_dipu_lib() {
    export DIOPI_ROOT=$PWD/third_party/DIOPI/DIOPI-IMPL/lib/
    export LIBRARY_PATH=$DIOPI_ROOT:$LIBRARY_PATH;

    autogen_diopi_wrapper
    config_dipu_cmake
    mkdir -p build && cd build && make -j8  2>&1 | tee ./build1.log &&  cd ..
    cp ./build/torch_dipu/csrc_dipu/libtorch_dipu.so   ./torch_dipu
    cp ./build/torch_dipu/csrc_dipu/libtorch_dipu_python.so   ./torch_dipu
}


if [[ "$1" == "builddiopi" ]]; then
    build_diopi_lib
elif [[ "$1" == "builddl" ]]; then
    build_dipu_lib
elif [[ "$1" == "builddp" ]]; then
    build_dipu_py
fi
