# Copyright (c) 2023, DeepLink.
import torch
import torch_dipu

torch.seed()
torch.manual_seed(1)
assert torch.cuda.initial_seed() == 1
assert torch.initial_seed() == 1
for i in range(torch.cuda.device_count()):
    torch.cuda.manual_seed(i)

state = torch.cuda.get_rng_state(0)
print("first state = ", state)
new_state = torch.ones_like(state)
torch.cuda.set_rng_state(new_state, 0)
current_state = torch.cuda.get_rng_state(0)
print("second state = ", current_state)

t1 = torch.arange(0, 100, dtype=torch.float32).cuda()
t2 = t1.clone()
torch.manual_seed(1)
t1.uniform_()
torch.manual_seed(1)
t2.uniform_()
print(f"t1 = {t1}")
print(f"t2 = {t2}")
assert torch.allclose(t1, t2)
t2.uniform_()
assert not torch.allclose(t1, t2)
print("uniform_ allclose success")

torch.manual_seed(1)
t1.normal_()
torch.manual_seed(1)
t2.normal_()
print(f"t1 = {t1}")
print(f"t2 = {t2}")
assert torch.allclose(t1, t2)
t2.normal_()
assert not torch.allclose(t1, t2)
print("normal_ allclose success")

torch.manual_seed(1)
t1.random_(0, 100)
torch.manual_seed(1)
t2.random_(0, 100)
print(f"t1 = {t1}")
print(f"t2 = {t2}")
assert torch.allclose(t1, t2)
t2.random_(0, 100)
assert not torch.allclose(t1, t2)
print("random_ allclose success")

torch.manual_seed(1)
t1.random_()
torch.manual_seed(1)
t2.random_()
print(f"t1 = {t1}")
print(f"t2 = {t2}")
assert torch.allclose(t1, t2)
t2.random_()
assert not torch.allclose(t1, t2)
print("random_ allclose success")

data = torch.arange(0, 100, dtype=torch.float).cuda()
torch.manual_seed(1)
data1 = torch.multinomial(data, 10)
torch.manual_seed(1)
data2 = torch.multinomial(data, 10)
print(f"data1 = {data1}")
print(f"data2 = {data2}")
assert torch.allclose(data1, data2)
data2 = torch.multinomial(data, 10)
assert not torch.allclose(data1, data2)
print("multinomial allclose success")

torch.manual_seed(1)
t1 = torch.randn(100, device='cuda')
torch.manual_seed(1)
t2 = torch.randn(100, device='cuda')
assert torch.allclose(t1, t2)
t2 = torch.randn(100, device='cuda')
assert not torch.allclose(t1, t2)
print("randn allclose success")

if torch_dipu.dipu.vendor_type != "MLU":
    torch.manual_seed(1)
    t1 = torch.randperm(100, device='cuda')
    torch.manual_seed(1)
    t2 = torch.randperm(100, device='cuda')
    assert torch.allclose(t1, t2)
    t2 = torch.randperm(100, device='cuda')
    assert not torch.allclose(t1, t2)
    print("randperm allclose success")