from torch_dipu.testing._internal import common_utils

TORCH_TEST_PRECIIONS = {
    # test_name : floating_precision,
    'test_pow_dipu_float32': 0.0035,
    'test_pow_dipu_float64': 0.0045,
    'test_var_neg_dim_dipu_bfloat16': 0.01,
    'test_sum_dipu_bfloat16': 0.1,
}

DISABLED_TORCH_TESTS_ANY = {
    # test_torch.py
    'TestDevicePrecisionDIPU': {
        'test_sum_cpu_device_mismatch', 
        'test_solve_methods_arg_device',  
        'test_min_max_nan',  
        'test_min_max_binary_op_nan',  
        'test_copy_broadcast',
    },
    # test_torch.py
    'TestTensorDeviceOpsDIPU': {
        'test_block_diag_scipy',  
        'test_mean_64bit_indexing_dipu', 
    },
    # test_torch.py
    'TestTorchDeviceTypeDIPU': {
        'test_addmm_sizes',  
        'test_addcmul', 
        'test_clamp',  
        'test_clamp_propagates_nans_dipu',  
        'test_cummax_cummin',  
        'test_cummax_discontiguous',  
        'test_cummin_discontiguous',  
        'test_diff_dipu_bool',  
        'test_diff_dipu_float32',  
        'test_diff_dipu_float64', 
        'test_diff_dipu_int16',  
        'test_diff_dipu_int32', 
        'test_diff_dipu_int64', 
        'test_diff_dipu_int8',  
        'test_diff_dipu_uint8', 
        'test_discontiguous_out_cumsum',  
        'test_invalid_shapes_grid_sampler_dipu', 
        'test_lu_unpack',  
        'test_view',  
        'test_sub_typing',  
        'test_reduction_empty',  
        'test_randperm',
        'test_pow',
        'test_pow_scalar_overloads_mem_overlap',  
        'test_pdist_norm',
        'test_pdist_norm_backward_dipu',  
        'test_pdist_norm_forward_dipu', 
        'test_nuclear_norm_axes_small_brute_force',
        'test_mul_intertype_scalar',
        'test_masked_select_discontiguous',  
        'test_memory_format_type',
        'test_memory_format_type_shortcuts',
        'test_memory_format_to',
        'test_memory_format_factory_like_functions_preserve_strides',
        'test_memory_format_empty_like',
        'test_memory_format_clone',
        'test_memory_format_factory_like_functions_preserve', 
        'test_memory_format_propagation_rules',  
        'test_max',  
        'test_min',  
        'test_min_max_binary_op_nan',
        'test_minmax_illegal_dtype',  
        'test_argminmax_multiple', 
        'test_mm_dipu_bfloat16',  
        'test_lu_solve_batched_non_contiguous',
        'test_linspace_dipu',  
        'test_lstsq',
        'test_is_set_to',
        'test_inverse',
        'test_empty_tensor_props',  
        'test_dist',
        'test_dim_function_empty',
        'test_diagflat',
        'test_cat_out', 
        'test_cumsum',
        'test_copy_mem_overlap', 
        'test_copy_all_dtypes_and_devices',
        'test_cholesky_solve_batched_non_contiguous',
        'test_cdist_norm',
        'test_cdist_norm_batch',
        'test_cdist_large',
        'test_cdist_large_batch',
        'test_cdist_non_contiguous',
        'test_cdist_non_contiguous_batch',
        'test_cov',  
        'test_broadcast_batched_matmul',  
        'test_bincount',
        'test_view_all_dtypes_and_devices',  
        'test_unfold_all_devices_and_dtypes', 
        'test_tensor_pow_tensor',  
        'test_tensor_factories_empty',  
        'test_svd',
        'test_svd_no_singularvectors',
        'test_svd_lowrank',
        'test_pca_lowrank',
        'test_lobpcg_basic',
        'test_lobpcg_ortho',
        'test_lobpcg_scipy',
        'test_lobpcg_torchscript',
        'test_storage_device', 
        'test_roll',
        'test_resize_as_all_dtypes_and_devices',  
        'test_resize_all_dtypes_and_devices',  
        'test_pinverse', 
        'test_norm',
        'test_multinomial',
        'test_multinomial_alias',
        'test_masked_select',  
        'test_masked_fill_bool_tensor',  
        'test_lu',
        'test_logical_and',  
        'test_logical_or',  
        'test_logical_xor',  
        'test_logical', 
        'test_logical_not',  
        'test_is_signed',  
        'test_has_storage_numpy',  
        'test_float_scalar_pow_float_tensor',  
        'test_flip',  
        'test_fill_all_dtypes_and_devices',  
        'test_eye',  
        'test_empty_strided', 
        'test_dlpack_conversion',  
        'test_dim_reduction',
        'test_det_logdet_slogdet_batched',  
        'test_ctor_with_numpy_array',  
        'test_contiguous',  
        'test_clone_all_dtypes_and_devices',  
        'test_cat_all_dtypes_and_devices', 
        'test_broadcast',
        'test_bitwise_not',
        'test_advancedindex',  
        'test_add',  
        'test_sign',
        'test_qr',  
        'test_std_mean_some_dims',  
        'test_det_logdet_slogdet',  
        'test_matrix_rank', 
        'test_triu_tril',
        'test_stft', 
        'test_strided_mismatched_stride_shape', 
        'test_strides_propagation',  
        'test_tensor_shape_empty',  
        'test_cholesky_inverse', 
        'test_cholesky_solve_batched',  
        'test_cholesky_solve', 
        'test_lu_solve_batched',  
        'test_lu_solve',  
        'test_solve_batched',  
        'test_solve',  
        'test_triangular_solve_batched',  
        'test_triangular_solve',  
        'test_scalar_check',  
        'test_argminmax_large_axis', 
        'test_randn_dipu_float32',  
        'test_randn_dipu_float64', 
        'test_rand_dipu_float32',  
        'test_rand_dipu_float64',  
        'test_normal', 
        'test_uniform_from_to',  
        'test_index_fill_dipu',  
        'test_dim_arg_reduction_scalar_dipu',  
        'test_storage',  
        'test_deepcopy',  
        'teeet_deepcopy_scalar', 
        'test_scatter_different_types', 
        'test_bernoulli_mem_overlap', 
        'test_cat_mem_overlap', 
        'test_gather_mem_overlap',  
        'test_index_put_mem_overlap', 
        'test_index_select_mem_overlap',  
        'test_linlogspace_mem_overlap', 
        'test_masked_fill_mem_overlap', 
        'test_masked_scatter_mem_overlap',  
        'test_masked_select_mem_overlap',  
        'test_scatter_mem_overlap',  
        'test_index_mem_overlap',  
        'test_maximum_minimum_complex',  
        'test_maximum_minimum_float_dipu_bfloat16', 
        'test_maximum_minimum_type_promotion_dipu_.*bfloat16.*',  
        'test_index_add_mem_overlap',  
        'test_shift_mem_overlap',  
        'test_muldiv_scalar_dipu_bfloat16',  
        'test_random_from_to_bool',  
        'test_random_from_to_dipu', 
        'test_random_to_dipu',  
        'test_copy_',  
        'test_assertRaisesRegex_ignore_msg_non_native_device_dipu', 
        'test_index_reduce',  
        'test_logcumsumexp_dipu', 
        'test_narrow_copy_non_contiguous',  
    },

    # test_view_ops.py
    'TestViewOpsDIPU': {
        'test_contiguous_nonview',
        'test_expand_as_view',
        'test_expand_view',
        'test_reshape_nonview',
        'test_unfold_view',
    },

    # test_indexing.py
    'TestIndexingDIPU': {
        'test_setitem_expansion_error',  
        'test_setitem_scalars',  
        'test_multiple_byte_mask',  
        'test_empty_slice',  
        'test_byte_tensor_assignment',  
        'test_byte_mask', 
        'test_byte_mask_accumulate', 
        'test_bool_indices',  
        'test_index_getitem_copy_bools_slices',  
        'test_index_setitem_bools_slices', 
        'test_getitem_scalars', 
        'test_empty_ndim_index',  
        'test_index_put_byte_indices_dipu', 
    },

    # test_indexing.py
    'NumpyTestsDIPU': {
        'test_trivial_fancy_out_of_bounds',  
        'test_boolean_assignment_value_mismatch', 
        'test_empty_tuple_index',  
        'test_empty_fancy_index',  
        'test_ellipsis_index',  
        'test_boolean_indexing_alldims',
        'test_boolean_indexing_onedim',
        'test_boolean_indexing_twodim',
        'test_boolean_list_indexing',
        'test_single_bool_index',
        'test_broaderrors_indexing',  
        'test_boolean_shape_mismatch',  
        'test_boolean_indexing_weirdness',  
        'test_boolean_indexing_weirdness_tensors',  
    },

    
    # test_type_promotion.py
    'TestTypePromotionDIPU': {
        'test_many_promotions',  
        'test_inplace',  
        'test_indexing', 
        'test_alternate_result',  
        'test_half',  
        'test_complex_promotion',  
        'test_complex_scalar_mult_tensor_promotion',  
        'test_div_promotion_inplace_dipu',  
    }
}

DISABLED_TORCH_TESTS_DIPU_ONLY = {
    # test_torch.py
    'TestDevicePrecisionDIPU': {
        'test_digamma',  
        'test_clamp_dipu_float64', 
    },
    'TestTensorDeviceOpsDIPU': {
        'test_pow_inplace_dipu', 
        'test_pow_inplace_3_dipu', 
        'test_pow_3_dipu',  
        'test_pow_-2_dipu',  
        'test_topk_dim_sort_dipu',  
        'test_topk_dim_desc_sort_dipu',  
        'test_sort_dipu', 
        'test_sort_neg_dim_dipu',  
        'test_sort_neg_dim_descending_dipu',  
        'test_sort_dim_dipu',  
        'test_sort_dim_descending_dipu',  
        'test_kthvalue_dipu',  
        'test_kthvalue_neg_dim_dipu',  
        'test_kthvalue_dim_dipu', 
        'test_eig_with_eigvec_dipu_float64',  
        'test_cumprod_dipu',  
        'test_cumprod_neg_dim_dipu', 
        'test_topk_neg_dim_sort_dipu', 
        'test_clamp_min_dipu_float64',  
        'test_clamp_min_inplace_dipu_float64', 
        'test_clamp_max_dipu_float64',  
        'test_clamp_max_inplace_dipu_float64',  
    },
    'TestTorchDeviceTypeDIPU': {
        'test_cholesky_solve_batched_broadcasting', 
        'test_cholesky_solve_batched_many_batches',  
        'test_triangular_solve_batched_many_batches',  
        'test_triangular_solve_batched_broadcasting',  
        'test_random_from_to_dipu_int32',  
        'test_uniform_from_to_dipu_float64',  
        'test_topk_integral_dipu_int64', 
        'test_float_to_int_conversion_finite_dipu', 
        'test_block_diag_scipy',  
        'test_remainder_fmod_large_dividend_dipu',  
        'test_logical_not_out_dipu', 
        'test_i0_range1_dipu_bfloat16', 
        'test_i0_range2_dipu_bfloat16', 
        'test_bucketization_dipu',  
        'test_median_real_values_dipu_int64', 
        'test_copysign_dipu.*bfloat16.*',  
        'test_nondeterministic_alert_bincount_dipu',  
        'test_nondeterministic_alert_histc_dipu',  
        'test_nondeterministic_alert_grid_sample_2d_dipu', 
        'test_nondeterministic_alert_grid_sample_3d_dipu',  
        'test_nondeterministic_alert_index_add_dipu',  
        'test_put_dipu_bfloat16',  
        'test_take_dipu_bfloat16', 
        'test_multinomial_constraints',  
        'test_multinomial_invalid_distribution', 
        'test_multinomial_invalid_dipu', 
        'test_softplus_low_threshold_dipu', 
        'test_put_dipu',  
        'test_cov_dipu',  
        'test_diff_dipu_float32',  
        'test_diff_dipu_float64',  
        'test_nullary_op_mem_overlap_dipu', 
        'test_index_reduce',  
        'test_take_dipu_float64', 
        'test_take_dipu_int16',  
    },

    # test_indexing.py
    'TestIndexingDIPU': {
        'test_index_put_accumulate_large_tensor_dipu',
    },
}


DISABLED_TORCH_TESTS_DIPU = common_utils.union_of_disabled_tests(
    [DISABLED_TORCH_TESTS_ANY, DISABLED_TORCH_TESTS_DIPU_ONLY])

DISABLED_TORCH_TESTS = {
    'DIPU': common_utils.prepare_match_set(DISABLED_TORCH_TESTS_DIPU),
}